/* Generated By:JavaCC: Do not edit this line. Assignment1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Assignment1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VARIABLE = 12;
  /** RegularExpression Id. */
  int CONSTANT = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int VOID = 17;
  /** RegularExpression Id. */
  int MAIN = 18;
  /** RegularExpression Id. */
  int TRUE = 19;
  /** RegularExpression Id. */
  int FALSE = 20;
  /** RegularExpression Id. */
  int WHILE = 21;
  /** RegularExpression Id. */
  int BEGIN = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int END = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int IS = 26;
  /** RegularExpression Id. */
  int SKIPTEXT = 27;
  /** RegularExpression Id. */
  int IDENTIFIER = 28;
  /** RegularExpression Id. */
  int LETTER = 29;
  /** RegularExpression Id. */
  int UNDERSCORE = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int PLUS = 33;
  /** RegularExpression Id. */
  int MINUS = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int SEMICOLON = 36;
  /** RegularExpression Id. */
  int COLON = 37;
  /** RegularExpression Id. */
  int COLONEQUALS = 38;
  /** RegularExpression Id. */
  int LEFTBRACKET = 39;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 40;
  /** RegularExpression Id. */
  int NOT = 41;
  /** RegularExpression Id. */
  int OR = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int EQUAL = 44;
  /** RegularExpression Id. */
  int NOTEQUAL = 45;
  /** RegularExpression Id. */
  int LT = 46;
  /** RegularExpression Id. */
  int GT = 47;
  /** RegularExpression Id. */
  int LET = 48;
  /** RegularExpression Id. */
  int GET = 49;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\" \"",
    "\"\\f\"",
    "\"\\t\"",
    "\"/*\"",
    "<token of kind 8>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"variable\"",
    "\"constant\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"begin\"",
    "\"if\"",
    "\"end\"",
    "\"else\"",
    "\"is\"",
    "\"skip\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<UNDERSCORE>",
    "<DIGIT>",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"~\"",
    "\"|\"",
    "\"&\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
  };

}
